### ISSUE TITLE
README update

### ISSUE THREAD

**Issue by maciejhirsz** [serde-rs/json-benchmark#1]
Should I update it from my own machine if I do stuff?

Results I'm getting now:

```
     Running `target/release/json-benchmark`
                                DOM                STRUCT
======= serde_json ======= parse|stringify === parse|stringify ===
data/canada.json          51.8ms    23.9ms    36.9ms    20.0ms
data/citm_catalog.json    30.2ms     3.3ms    20.6ms     1.7ms
data/twitter.json         10.3ms     1.4ms     8.4ms     1.4ms

======= json-rust ======== parse|stringify === parse|stringify ===
data/canada.json          42.0ms    42.3ms
data/citm_catalog.json    16.3ms     2.0ms
data/twitter.json          6.7ms     1.1ms

==== rustc_serialize ===== parse|stringify === parse|stringify ===
data/canada.json          39.7ms    68.8ms    48.0ms    65.0ms
data/citm_catalog.json    26.8ms     6.1ms    32.7ms     4.1ms
data/twitter.json         13.4ms     2.8ms    17.9ms     2.6ms
```

This is using a branch of `json-rust` that can directly write to `io::Write` types. The performance is somewhat aligned, although the difference is smaller (and `serde_json` writing to a struct is faster).

It is accounted for by the fact that `io::Write` doesn't implement a method that allows to write a single `u8`, so all single token writes have to be wrapped into a `&[u8]` slice which creates an unnecessary level of indirection.

**Comment by dtolnay** [comment]
I added my results in 18828fc00f9df710c95b2799c2f3bc69cfbe7c3a. https://github.com/maciejhirsz/json-rust/issues/52 affects the conformance result.
