### ISSUE TITLE
Update GCC/Clang versions

### ISSUE THREAD

**Issue by ZaMaZaN4iK** [serde-rs/json-benchmark#15]
Hi!

Seems like comparison isn't fair enough since you use outdated C++ compilers but quite new Rust compiler. Please update to the latest GCC10/Clang10.

Thank you.

**Comment by dtolnay** [comment]
Thanks, indeed I hadn't updated the C++ numbers since 2016 (when those compiler version were both brand new).

**Comment by dtolnay** [comment]
FYI @Licenser since it appears now rapidjson's stringify of citm_catalog.json is now some 2x faster than simd-json's; maybe this is actionable to you.

Here is the repro:

```bash
  # simd-json
$ CARGO_INCREMENTAL=0 RUSTFLAGS='-C codegen-units=1 -C target-cpu=native' cargo build --release --no-default-features --features stringify-dom,lib-simd-json,file-citm-catalog
$ target/release/json-benchmark

  # rapidjson
$ git fetch origin refs/pull/16/head  # https://github.com/serde-rs/json-benchmark/commit/e07d3e754e1efcbfd2b488614de0d02285ab9e45
$ git checkout FETCH_HEAD
$ cd cpp
$ make
$ ./benchmark
```
