### ISSUE TITLE
Remove json-rust from benchmark?

### ISSUE THREAD

**Issue by ecton** [serde-rs/json-benchmark#21]
In an attempt to try to find a good JSON DOM library that supports borrowing, I came across this benchmark and almost used the `json` crate. I found it odd that the crates.io listing has no README, yet it's such a popular crate and performs quite well!

Then I saw on github that [it isn't maintained](https://github.com/maciejhirsz/json-rust/issues/205). Not a problem if it's done with development, as a JSON library certainly could be. But another issue [points out a soundness issue](https://github.com/maciejhirsz/json-rust/issues/196) that Miri also doesn't like.

Given that it's unmaintained and potentially unsound, I'm not sure how valid of a comparison it actually provides in today's JSON ecosystem. In fact, I worry that the mere presence of it on this list might be leading some developers to adopt the crate despite, in my opinion, it not being a safe crate to adopt given the open issues.

**Comment by dtolnay** [comment]
Oh that's too bad, I liked that crate a lot. :(

I agree a UB issue open for 2 years without response is concerning and we should avoid recommending the crate at this point. Could you send a PR to remove it from the readme and remove the relevant benchmark code from the implementation? I would love to put it back later if the crate becomes maintained again.

Thank you for raising this.

**Comment by ecton** [comment]
Absolutely will send in a PR. Thank you for the prompt reply (and your countless other contributions to the ecosystem)!
