### ISSUE TITLE
Add a note regarding conformance?

### ISSUE THREAD

**Issue by maciejhirsz** [serde-rs/json-benchmark#3]
I did make an issue about it on the original [nativejson-benchmark](https://github.com/miloyip/nativejson-benchmark/issues/51), thus far unanswered.

The conformance tests of the nativejson-benchmark aren't actually testing conformance with ECMA or RFC, despite what the README says. Taking the roundtrip tests:

- `roundtrip10.json` will fail on any implementation that doesn't preserve ordering of the keys, not required by the standard (I pass it by the virtue of the keys being in alphabetical order).
- `roundtrip13.json`, `roundtrip14.json`, `roundtrip18.json` and `roundtrip19.json` all require higher precision than IEEE 754 float64, this is not required by the standard.
- `roundtrip20.json` requires that a floating point zero is different from an integer zero, and is represented with a fraction, this is not required by the standard.
- `roundtrip21.json` again requires different representation of floating zero, and requires that negative zero is preserved, not requirements of the standard.
- `roundtrip24.json`, `roundtrip25.json`, `roundtrip26.json` and `roundtrip27.json` requires that `e` notation is written with a lower case `e` and that positive exponents are written without a plus. Any implementation that writes capital `E` and/or adds a `+` to positive exponents would fail this.

Web browsers and Node.js would fail 7 of those tests, while being perfectly within the standard.

I don't know if my original issue is going to be resolved, but should we add a note that this is a conformance test as it is ported from `nativejson-benchmark` and is not actually testing conformance to JSON standard as it is?

**Comment by dtolnay** [comment]
I agree, the roundtrip tests are pretty silly. How would you feel about deleting the conformance tests altogether? I already filed https://github.com/serde-rs/json/issues/113 to bring the ones we care about into serde_json.

**Comment by maciejhirsz** [comment]
Quite fine with dropping them entirely. They are useful and can catch edge cases, but they should be more of an interest to library authors than general public using those libraries.
